# -*- coding: utf-8 -*-
"""Copia de Lab 8.2 Navar_Gabriel functions & Subprogram, -  Intro Recursion.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TVxHeJIWhhKk5ryuPHUW2REGDTnnVfc

# Structured Programming

## Lab 8. Subprograms and Recursion

### Learning Objectives

By the end of this worksheet, you will be able to:

* Differentiate between functions and procedures.
* Identify the basic structure of subprograms.
* Create functions and procedures in Python.
* Understand the concept of recursion.
* Implement simple recursive functions.



# Part 1. Reviewing Functions

Observe the following code and execute it.
"""

def calculate_final_grade(exam1, exam2, project):
  pass

final_grade = calculate_final_grade(85, 92, 88)
print(final_grade)

"""

### Reflection Questions

1. What value does the function return?

---

2. Where is the result stored?

---

3. What would happen if the `return` statement were removed?

---



# Part 2. What Is a Procedure?

In structured programming, there are two main types of subprograms:

## Function

A function performs a task and returns a value.

Example:

"""

def calculate_area(base, height):
    return base * height

area = calculate_area(5, 4)

print(area)

"""

## Procedure

A procedure performs an action but does not return a value.

Example:

"""

def display_menu():
    print("1. Add")
    print("2. Subtract")
    print("3. Exit")

display_menu()

"""

### Activity 1

Execute the following code.

"""

def greet(name):
    print("Hello", name)

result = greet("Anna")

print(result)

"""### Questions

1. What appears first on the screen?

---

2. What is stored in the variable `result`?

---

3. Does the subprogram return a value?

---



# Part 3. Identifying Functions and Procedures

Analyze each subprogram.

```python
def get_name():
    return input("Name: ")

def print_report():
    print("Report generated")

def calculate_average(a, b, c):
    return (a + b + c) / 3

def display_message():
    print("Welcome")
```

Complete the table.

| Subprogram        | Function or Procedure |
| ----------------- | --------------------- |
| get_name          |                       |
| print_report      |                       |
| calculate_average |                       |
| display_message   |                       |




# Part 4. Creating Procedures

## Guided Exercise

Complete the following procedure.
"""

def display_header():
    # Write three lines of text
    pass

display_header()

#Challenge 1

"""
Expected output:

```text
University
Structured Programming
Subprogram Practice
```

---

## Challenge

Create a procedure called `display_table_of_5()` that prints the multiplication table of 5.

Expected output:

```text
5 x 1 = 5
5 x 2 = 10
...
5 x 10 = 50
```



"""



"""


# Part 5. Creating Functions

## Guided Exercise

Complete the following function.
"""

def square(number):
    pass #remember this is the instruction to do nothing, you have to replace it

print(square(4))

"""

Expected output:

```text
16
```



## Challenge

Create a function called `is_even(number)`.

The function must return:

* True if the number is even.
* False if the number is odd.

Test your function:

```python
print(is_even(8))
print(is_even(7))
```

"""

#Write your code here

"""

# Part 6. Introduction to Recursion

A recursive function is a function that calls itself.

Observe the following example.

"""

def countdown(n):

    print(n)

    if n > 1:
        countdown(n - 1)

countdown(5)

"""

Execute the program.

### Questions

1. Which numbers are displayed?

---The numbers displayed are 5, 4, 3, 2, 1 (each on a new line)

2. What happens when `n` becomes 1?

---When $n$ is 1, the line print(n) executes and prints 1. Then, the condition if n > 1: is evaluated. Since $1 > 1$ is False, the recursive call countdown(n - 1) is skipped

3. Why does the program stop?

---The program stops because the if statement acts as the base case. By preventing the function from calling itself again when $n$ is no longer greater than 1, it breaks the cycle of recursion, allowing the function calls to finish and the program to terminate.



# Part 7. Understanding the Base Case

Every recursive function needs a condition that stops the recursion.

Observe the following example.

"""

def say_hello(n):

    if n == 0:
        return

    print("Hello")
    say_hello(n - 1)

say_hello(4)

"""### Questions

1. How many times is "Hello" printed?

---say_hello(4) prints "Hello", calls say_hello(3)

say_hello(3) prints "Hello", calls say_hello(2)

say_hello(2) prints "Hello", calls say_hello(1)

say_hello(1) prints "Hello", calls say_hello(0)

say_hello(0) hits the base case and returns without printing

2. What is the base case?

---if n == 0:
    return

3. What would happen if the `if` statement were removed?

---If the if statement were removed, the function would have no "exit" condition. It would keep calling itself indefinitely with decreasing values of $n$ ($4, 3, 2, 1, 0, -1, -2)


# Part 8. Building a Recursive Function

Complete the following function.


"""

def count_to_one(n):

    print(n)

    if n > 1:
        count_to_one(n - 1)

count_to_one(10)

"""Observe carefully how the function calls itself.

### Reflection

What is the role of the statement:

```python
count_to_one(n - 1)
```

*Answer*
---


# Part 9. First Recursive Mathematical Example

The factorial of a number is defined as:

```text
4! = 4 × 3 × 2 × 1
```

Observe the following code.

```python
def factorial(n):

    if n == 1:
        return 1

    return n * factorial(n - 1)

print(factorial(4))
```

### Activity

Complete the table.

| Function Call | Waiting For |
| ------------- | ----------- |
| factorial(4)  |             |
| factorial(3)  |             |
| factorial(2)  |             |
| factorial(1)  |             |

---

### Reflection

Why does the function eventually stop?

---When n reaches 1, the function no longer calls itself. Instead, it returns the value 1. This allows the previous function calls in the stack to finally complete their own calculations (e.g., $2 \times 1 = 2$, then $3 \times 2 = 6$, and finally $4 \times 6 = 24$),

---

---

# Part 10. Final Challenge

Create a program that includes:

## Procedures

* display_menu()
* say_goodbye()

## Functions

* calculate_area()
* calculate_average()

## Recursive Function

* countdown()

The menu should allow the user to select an option.

```text
1. Calculate Area
2. Calculate Average
3. Countdown
4. Exit
```

### Requirements

* Use at least two procedures.
* Use at least two functions that return values.
* Use one recursive function.
* Organize the program into subprograms.


1. What is the difference between a function and a procedure?

---Function: Designed to perform a specific task and return a value to the part of the program that called it. You use functions when you need to calculate or process data and get a result back (e.g., calculate_area returns a numeric result

---

2. What is recursion?

---Recursion is a programming technique where a function calls itself to solve a problem. It works by breaking a complex problem down into smaller, simpler versions of the same problem. Each time the function calls itself, it gets closer to the final solution



3. Why does every recursive function need a base case?

---Without a base case, the function would call itself infinitely (or until the computer runs out of memory), resulting in a "stack overflow" error.

---

4. Which topic was most difficult for you?

---Tip for success: If recursion feels tricky, try drawing out the "stack" on a piece of paper—write down every call the function makes until it hits the base case, and then write down the return values as they "pop" back up the stack

---
"""



"""# References

Downey, A. (2024). *Think Python: How to Think Like a Computer Scientist*. Green Tea Press.

Python Software Foundation. *Python Documentation*. Available at: https://docs.python.org/

Gaddis, T. (2023). *Starting Out with Python* (6th Edition). Pearson.


# Submission Instructions

To receive credit for this activity, complete the following steps:

1. Make a copy of the notebook and save it in your personal repository.

2. Complete all sections of the worksheet:

   * Run every example provided.
   * Answer all reflection questions.
   * Complete all guided exercises.
   * Complete all challenge activities.

3. Verify that all code cells execute correctly before submitting.

4. Once the notebook is finished, mark the assignment as **Completed** in Google Classroom.



# Additional Practice

You are encouraged to improve your solutions by adding:

* Input validation
* Error handling
* Additional menu options
* More descriptive output messages

These improvements are optional but highly recommended as a way to strengthen your programming skills and gain additional practice with structured programming concepts.

"""