# -*- coding: utf-8 -*-
"""Lab 8. Functions & Subprogram, -  Intro Recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVvislQ-cy_iGcBvg5_nbCBit3PT2NI7

# Structured Programming

## Lab 8. Subprograms and Recursion

### Learning Objectives

By the end of this worksheet, you will be able to:

* Differentiate between functions and procedures.
* Identify the basic structure of subprograms.
* Create functions and procedures in Python.
* Understand the concept of recursion.
* Implement simple recursive functions.



# Part 1. Reviewing Functions

Observe the following code and execute it.
"""

def calculate_final_grade(exam1, exam2, project):
  return (exam1 + exam2 + project) / 3

final_grade = calculate_final_grade(85, 92, 88)
print(final_grade)

"""

### Reflection Questions

1. What value does the function return?

---  The grade

2. Where is the result stored?

In final grade

---

3. What would happen if the `return` statement were removed?

--- Print none



# Part 2. What Is a Procedure?

In structured programming, there are two main types of subprograms: To perform a specific task

## Function

A function performs a task and returns a value.

Example:base * height

"""

def calculate_area(base, height):
    return base * height

area = calculate_area(5, 4)

print(area)

"""

## Procedure

A procedure performs an action but does not return a value.

Example:

"""

def display_menu():
    print("1. Add")
    print("2. Subtract")
    print("3. Exit")

display_menu()

"""

### Activity 1

Execute the following code.

"""

def greet(name):
    print("Hello", name)

result = greet("Anna")

print(result)

"""### Questions

1. What appears first on the screen?

---Print hello Anna and none

2. What is stored in the variable `result`?

---To greet Anna

3. Does the subprogram return a value?

--- NO



# Part 3. Identifying Functions and Procedures

Analyze each subprogram.

```python
def get_name():
    return input("Name: ")

def print_report():
    print("Report generated")

def calculate_average(a, b, c):
    return (a + b + c) / 3

def display_message():
    print("Welcome")
```

Complete the table.

| Subprogram        | Function or Procedure |
| ----------------- | --------------------- |
| get_name          |                       |
| print_report      |                       |
| calculate_average |                       |
| display_message   |                       |




# Part 4. Creating Procedures

## Guided Exercise

Complete the following procedure.
"""

def display_header():
    # Write three lines of text
    pass

display_header()
display_university:()
display_subprogram:()
display_Structured_Programming:()

"""
Expected output:

```text
University
Structured Programming
Subprogram Practice
```

---

## Challenge

Create a procedure called `display_table_of_5()` that prints the multiplication table of 5.

Expected output:

```text
5 x 1 = 5
5 x 2 = 10
...
5 x 10 = 50
```



# Part 5. Creating Functions

## Guided Exercise

Complete the following function.

"""

display_table_of_5:()
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 =25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

def square(number):
    pass #remember this is the instruction to do nothing, you have to replace it
return int (value)
print(square(4))

"""

Expected output:

```text
16
```



## Challenge

Create a function called `is_even(number)`.

The function must return:

* True if the number is even.
* False if the number is odd.

Test your function:

```python
print(is_even(8))
print(is_even(7))
```

"""

true=(bool)
false=(bool)
number=input(float)
is_even=int(input)


if the number is true:
  print(is_even(8))
elif:
  print(is_even(7))
  return value

"""

# Part 6. Introduction to Recursion

A recursive function is a function that calls itself.

Observe the following example.

"""

def countdown(n):

    print(n)

    if n > 1:
        countdown(n - 1)

countdown(5)

"""

Execute the program.

### Questions

1. Which numbers are displayed?

---

2. What happens when `n` becomes 1?

---

3. Why does the program stop?

---



# Part 7. Understanding the Base Case

Every recursive function needs a condition that stops the recursion.

Observe the following example.

"""

def say_hello(n):

    if n == 0:
        return

    print("Hello")
    say_hello(n - 1)

say_hello(4)

"""### Questions

1. How many times is "Hello" printed?

---

2. What is the base case?

---

3. What would happen if the `if` statement were removed?

---


# Part 8. Building a Recursive Function

Complete the following function.


"""

def count_to_one(n):

    print(n)

    if n > 1:
        count_to_one(n - 1)

count_to_one(10)

"""Observe carefully how the function calls itself.

### Reflection

What is the role of the statement:

```python
count_to_one(n - 1)
```

*Answer*
---


# Part 9. First Recursive Mathematical Example

The factorial of a number is defined as:

```text
4! = 4 × 3 × 2 × 1
```

Observe the following code.

```python
def factorial(n):

    if n == 1:
        return 1

    return n * factorial(n - 1)

print(factorial(4))
```

### Activity

Complete the table.

| Function Call | Waiting For |
| ------------- | ----------- |
| factorial(4)  |             |
| factorial(3)  |             |
| factorial(2)  |             |
| factorial(1)  |             |

---

### Reflection

Why does the function eventually stop?

---

---

---

# Part 10. Final Challenge

Create a program that includes:

## Procedures

* display_menu()
* say_goodbye()

## Functions

* calculate_area()
* calculate_average()

## Recursive Function

* countdown()

The menu should allow the user to select an option.

```text
1. Calculate Area
2. Calculate Average
3. Countdown
4. Exit
```

### Requirements

* Use at least two procedures.
* Use at least two functions that return values.
* Use one recursive function.
* Organize the program into subprograms.


1. What is the difference between a function and a procedure?

---

---

2. What is recursion?

---

---

3. Why does every recursive function need a base case?

---

---

4. Which topic was most difficult for you?

---

---

# References

Downey, A. (2024). *Think Python: How to Think Like a Computer Scientist*. Green Tea Press.

Python Software Foundation. *Python Documentation*. Available at: https://docs.python.org/

Gaddis, T. (2023). *Starting Out with Python* (6th Edition). Pearson.


# Submission Instructions

To receive credit for this activity, complete the following steps:

1. Make a copy of the notebook and save it in your personal repository.

2. Complete all sections of the worksheet:

   * Run every example provided.
   * Answer all reflection questions.
   * Complete all guided exercises.
   * Complete all challenge activities.

3. Verify that all code cells execute correctly before submitting.

4. Once the notebook is finished, mark the assignment as **Completed** in Google Classroom.



# Additional Practice

You are encouraged to improve your solutions by adding:

* Input validation
* Error handling
* Additional menu options
* More descriptive output messages

These improvements are optional but highly recommended as a way to strengthen your programming skills and gain additional practice with structured programming concepts.
"""