# -*- coding: utf-8 -*-
"""Lab 10 Navar_Gabriel  Python File Handling.ip

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXvtnhxp-QjI2panGrWKYZo1wmc-Rdww

# Lab 10. Python File Handling
Name: _________Navar Gabriel__________________.
Date: ___________July 1st 2026____________.

In this notebook, *students* will learn how to interact with the file system using Python. This is a crucial skill for data processing, logging, and configuration management.

### Key Concepts:
- **`open()` function**: The primary way to open a file.
- **Modes**: `'r'` (read), `'w'` (write), `'a'` (append).
- **Context Managers (`with` statement)**: The best practice to ensure files are closed automatically.

## 1. Writing vs Overwriting

When you open a file in `'w'` mode, Python creates the file if it doesn't exist. **Warning:** If the file already exists, `'w'` will delete everything inside it before writing new data.
"""

# Creating a fresh file
with open('students.txt', 'w', encoding='utf-8') as f:
    f.write('Alice\nBob\nCharlie')

print("File 'students.txt' created with initial names.")

"""## 2. Iterating Over Lines

For large files, it is inefficient to use `.read()`. Instead, we can loop over the file object to process one line at a time. This saves memory.
"""

print("Reading names from the file:")
with open('students.txt', 'r', encoding='utf-8') as f:
    for line in f:
        # .strip() removes the newline character '\n'
        print(f"Student: {line.strip()}")

"""## 3. Appending to a File

Use the `'a'` mode to add content to the end of an existing file without deleting its previous content.
"""

with open('ejemplo.txt', 'a', encoding='utf-8') as f:
    f.write('\nThis line was appended later!')

with open('ejemplo.txt', 'r') as f:
    print(f.read())

"""# Student Exercises

Now it's your turn! Complete the following tasks to practice.

### Exercise 1: The Guest Book
Write a script that asks the user for their name and saves it into a file called `guest_book.txt`.
"""

# Exercise 1 Solution
name = input("Enter your name: ")
with open('guest_book.txt', 'w') as f:
    f.write(name)
print(f"Success! '{name}' has been written to guest_book.txt.")

"""### Exercise 2: Word Counter
Read the file `ejemplo.txt` and count how many words are in it. (Hint: use `.split()` on the string).
"""

# Exercise 2 Solution
try:
    with open('ejemplo.txt', 'r') as f:
        content = f.read()
        words = content.split()
        print(f"The file contains {len(words)} words.")
except FileNotFoundError:
    print("Please run the first cells of the notebook to create the file first.")

"""### Exercise 3: File Copy Tool
Write a program that reads the content of `students.txt` and writes it into a new file called `students_backup.txt`. This is a common real-world task.
"""

try:
    with open('students.txt', 'r') as f:
        content = f.read()
        words = content.split()
    with open('students_backup.txt', 'w') as backup_f:
        backup_f.write(content)
        print(f"The file contains {len(words)} words.")
except FileNotFoundError:
    print("Please run the first cells of the notebook to create the file first.")

"""## Resources & Bibliography

For further reading and deep dives into Python file management, you can refer to the following resources:

1. **Python Official Documentation**: [Reading and Writing Files](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files) - The authoritative guide on the subject.
2. **W3Schools**: [Python File Handling](https://www.w3schools.com/python/python_file_handling.asp) - Great for quick syntax references and interactive examples.
3. **Real Python**: [Reading and Writing Files in Python (Guide)](https://realpython.com/read-write-files-python/) - An in-depth article covering advanced techniques and performance.
4. **GeeksforGeeks**: [File Handling in Python](https://www.geeksforgeeks.org/file-handling-python/) - Explains all modes and methods with clear code snippets.
"""